defaults: ../../grpo_math_1B.yaml
grpo:
  num_prompts_per_step: 32
  num_generations_per_prompt: 16
  max_num_steps: 100
  val_period: 25
  val_at_start: true
  val_at_end: true
checkpointing:
  checkpoint_dir: results/dapo-gemma3-27b-it-2n8g
policy:
  model_name: google/gemma-3-27b-it
  tokenizer:
    name: google/gemma-3-27b-it
  train_micro_batch_size: 1
  max_total_sequence_length: 4096
  dtensor_cfg:
    activation_checkpointing: true
    tensor_parallel_size: 2
  dynamic_batching:
    enabled: true
  sequence_packing:
    enabled: false
  make_sequence_length_divisible_by: 8
  optimizer:
    name: "torch.optim.AdamW"
    kwargs:
      lr: 1.0e-06
  scheduler:
  - name: torch.optim.lr_scheduler.LinearLR
    kwargs:
      start_factor: 0.1
      end_factor: 1
      total_iters: 10
  - name: torch.optim.lr_scheduler.ConstantLR
    kwargs:
      factor: 1
      total_iters: 10000000000
  - milestones:
    - 10
  generation:
    max_new_tokens: 2048
    vllm_cfg:
      tensor_parallel_size: 4
      max_model_len: 4096
data:
  max_input_seq_length: 2048
  train:
    dataset_name: DAPOMath17K
  validation:
    dataset_name: DAPOMathAIME2024
logger:
  log_dir: logs/dapo-gemma3-27b-it-2n8g
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemorl-gemma3
    name: dapo-gemma3-27b-it-2n8g
cluster:
  gpus_per_node: 8
  num_nodes: 2
